### PR TITLE
DFS program in python

### PR DESCRIPTION
**Pull request by Tr0nML**

### CODE REVIEW

**Comment by Tr0nML** [comment]
participating in hacktoberfest

**Comment by Tr0nML** [comment]
please check and merge

**Comment by Tr0nML** [comment]
can u please tag hacktober accepted tag

**Comment by Mohit29750** [comment]
It will be counted in hacktober as i have given hacktober topic to my repository

**Comment by Mohit29750** [comment]
If you want you can raise more PR in it will add hacktober-accepted tag

**Comment by Tr0nML** [comment]
ok sure sir

**Pull request merged**
